MERGE INTO GENRE AS t
USING (VALUES (1,'なし',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)) AS i(ID,NAME,CREATED_AT,UPDATED_AT)
ON t.id = i.id
WHEN MATCHED THEN
   UPDATE SET (ID,NAME,CREATED_AT,UPDATED_AT) = (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT)
WHEN NOT MATCHED THEN
   INSERT (ID,NAME,CREATED_AT,UPDATED_AT) VALUES (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT);
MERGE INTO GENRE AS t
USING (VALUES (2,'技術書',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)) AS i(ID,NAME,CREATED_AT,UPDATED_AT)
ON t.id = i.id
WHEN MATCHED THEN
   UPDATE SET (ID,NAME,CREATED_AT,UPDATED_AT) = (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT)
WHEN NOT MATCHED THEN
   INSERT (ID,NAME,CREATED_AT,UPDATED_AT) VALUES (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT);
MERGE INTO GENRE AS t
USING (VALUES (3,'経済書',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)) AS i(ID,NAME,CREATED_AT,UPDATED_AT)
ON t.id = i.id
WHEN MATCHED THEN
   UPDATE SET (ID,NAME,CREATED_AT,UPDATED_AT) = (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT)
WHEN NOT MATCHED THEN
   INSERT (ID,NAME,CREATED_AT,UPDATED_AT) VALUES (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT);
MERGE INTO GENRE AS t
USING (VALUES (4,'雑誌',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)) AS i(ID,NAME,CREATED_AT,UPDATED_AT)
ON t.id = i.id
WHEN MATCHED THEN
   UPDATE SET (ID,NAME,CREATED_AT,UPDATED_AT) = (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT)
WHEN NOT MATCHED THEN
   INSERT (ID,NAME,CREATED_AT,UPDATED_AT) VALUES (i.id,i.NAME,i.CREATED_AT,i.UPDATED_AT);
